config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "blogs#index"
  resources :blogs
  resources :users  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :move_to_index, except: :index

  def index
    @blogs = Blog.order("created_at DESC").page(params[:page]).per(5)
  end

  def new
  end

  def create
    @blog = Blog.new(text: blog_params[:text], user_id: current_user.id)
    if @blog.save
      redirect_to root_path, notice: '投稿が完了しました'
    else
      redirect_to new_blog_path, alert: "本文を入力してください"
    end
  end

  def destroy
    blog = Blog.find(params[:id])
    blog.destroy if blog.user_id == current_user.id
    redirect_to root_path, notice: '削除が完了しました'
  end

  def edit
    @blog = Blog.find(params[:id])
  end
  
  def update
    blog = Blog.find(params[:id])
    blog.update(blog_params)if blog.user_id == current_user.id
    redirect_to root_path, notice: '編集が完了しました'
  end

  private
  def blog_params
    params.permit(:text)
  end

  def move_to_index
    redirect_to action: "index" unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_message.html.haml
- blogs.each do |blog|
  .row
    .col.s12.m6
      .card.white
        .card-content.black-text
          %p
            = blog.text
        - if user_signed_in? && current_user.id == blog.user_id
          .card-action
            = link_to 'Edit', "/blogs/#{blog.id}/edit", method: :get
            = link_to 'Delete', "/blogs/#{blog.id}", method: :delete

app/views/blogs/create.html.haml
%p 投稿が完了しました！
= link_to "トップへ戻る", "/blogs"

app/views/blogs/destory.html.haml
.contents.row
  .success
    %h3
      削除が完了しました。
    %a.btn{:href => "/"} 投稿一覧へ戻る

app/views/blogs/edit.html.haml
.contents.row
  = form_with url: blog_path, method: :patch, local: true do |form|
    %h6
      編集する
    = form.text_field :text, value: @blog.text, class:'textarea'
    = form.submit "編集" 

app/views/blogs/index.html.haml
.messages
  = render "message", blogs: @blogs
= paginate(@blogs)

app/views/blogs/new.html.haml
.contents
  %h6 本文
  = form_with url: blogs_path, local: true do |form|
    = form.text_field :text, class:'textarea'
    = form.submit "投稿"

app/views/blogs/update.html.haml
.contents.row
  .success
    %h3
      更新が完了しました。
    %a.btn{:href => "/"} 投稿一覧へ戻る

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

-# :javascript
-#   $(function(){
-#     setTimeout("$('.notification').fadeOut('slow')", 1000) 
-#   })

:javascript
  $('.notification').click(function(){
    $('.notification').fadeOut('slow')
  })

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title MiniApp1
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    / Compiled and minified CSS
    %link{href: "https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css", rel: "stylesheet"}/
    / Compiled and minified JavaScript
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"}
    %script{crossorigin: "anonymous", integrity: "sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=", src: "https://code.jquery.com/jquery-3.4.1.js"}
  %body
    = render 'layouts/notifications'
    %nav
      %div.nav-wrapper
        %a.brand-logo{href: "/blogs"} Mini-App-Blog
        - if user_signed_in?
          %ul#nav-mobile.right.hide-on-med-and-down
            %li
              %a{"data-method": "delete", href: "/users/sign_out"} Sign Out
            %li
              %a{href: "/blogs/new"} New
        - else
          %ul#nav-mobile.right.hide-on-med-and-down
            %li
              %a{href: "/users/sign_in"} Log In
            %li
              %a{href: "/users/sign_up"} Sign Up
    = yield
    